# Generated by Django 6.0.2 on 2026-02-09 08:47

import autoslug.fields
import taggit.managers
from django.db import migrations

import gallery.utils


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="screencap",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from=gallery.utils.title_slug, unique=True
            ),
        ),
    ]
