# Generated by Django 6.0.2 on 2026-02-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_screencap_tags_alter_title_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="screencap",
            name="height",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="screencap",
            name="width",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="screencap",
            name="image",
            field=models.ImageField(
                height_field="height", upload_to="screencaps/", width_field="width"
            ),
        ),
    ]
