# Generated by Django 6.0.2 on 2026-02-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_screencap_height_screencap_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
    ]
