# Generated by Django 6.0.2 on 2026-03-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_title_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="type",
            field=models.CharField(
                choices=[("MOVIE", "Movie"), ("SERIES", "TV Show")],
                db_index=True,
                default="MOVIE",
                max_length=10,
            ),
        ),
    ]
